# https://github.com/rytswd/comvent
trigger: default

keywords:
  - name: confirm-bug
    value: '\/((C|c)onfirm.*)'

  - name: close-duplicate
    value: '\/(D|d)uplicate.*'

  - name: close-invalid
    value: '\/(I|i)nvalid.*'

  - name: good-first-issue
    # example: /good-first-issue
    value: '\/(G|g)ood[\s-]*(F|f)irst[\s-]*(I|i)ssue.*'

  - name: help-wanted
    # example: /help-wanted
    value: '\/(H|h)elp[\s-]*(W|w)anted.*'

  - name: retry-jobs
    # example: /retry, /rerun
    value: '\/(([Rr])etry|([Rr])erun).*'
